import { Game } from "@/types/game";

export const getSaleGames = (): Game[] => {
  return [
    {
      id: "1",
      title: "Battlefield™ 6",
      originalPrice: "1,699,000 ₴",
      discountedPrice: "1,189,30 грн.",
      discount: 30,
      imageUrl: "/images/games/battlefield-6.jpg",
      tags: ["Гостине", "Норвегія Liquacy"],
      developer: "EA DICE",
      platforms: ["Windows"],
      price: undefined,
      image: undefined,
      description:
        "Нова частина легендарної серії тактичних шутерів. Battlefield 6 повертається до сучасного сеттингу з масштабними битвами на 128 гравців, руйнованим середовищем та реалістичною фізикою. Режим Hazard Zone пропонує напружений командний екшен з перманентною смертю.",
    },
    {
      id: "2",
      title: "EA SPORTS FC™ 28 Standard Edition",
      originalPrice: "1,699,000 ₴",
      discountedPrice: "673,00 грн.",
      discount: 60,
      imageUrl: "/images/games/fc28.jpg",
      tags: ["Доступний пробний період"],
      developer: "EA Sports",
      platforms: ["Windows", "PlayStation"],
      price: undefined,
      image: undefined,
      description:
        "Продовження футбольної симуляції від EA під новим брендом. Покращена система HyperMotionV на основі машинного навчання, реалістична анімація гравців та оновлений режим кар'єри. Для фанатів футболу - обов'язкова покупка, особливо зі знижкою 60%.",
    },
    {
      id: "3",
      title: "Borderlands 4",
      originalPrice: "2,099,000 ₴",
      discountedPrice: "1,469,30 грн.",
      discount: 30,
      imageUrl: "/images/games/borderlands-4-fnnpo.jpg",
      tags: ["Провальний хіт став легендою"],
      developer: "Gearbox Software",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Лутеровий шутер повертається з новими Ваххандами, мільйонами видів зброї та безумним гумором. Кооператив на 4 особи, масштабніший світ ніж будь-коли та революційна система кастомізації зброї. Ідеально для гри з друзями.",
    },
    {
      id: "4",
      title: "ARK: Riders",
      originalPrice: "1,499,000 ₴",
      discountedPrice: "1,049,30 грн.",
      discount: 30,
      imageUrl: "/images/games/arc.avif",
      tags: ["Новий світ, нові пригоди"],
      developer: "Studio Wildcard",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Спін-офф серії ARK з акцентом на верхову їзду та повітряні битви на драконах. Досліджуйте плавучий архіпелаг, приручайте міфічних істот та беріть участь у масштабних PvP битвах. Для любителів динозаврів та фентезі.",
    },
    {
      id: "5",
      title: "Death Stranding 2",
      originalPrice: "2,299,000 ₴",
      discountedPrice: "1,609,30 грн.",
      discount: 30,
      imageUrl: "/images/games/death.jpg",
      tags: ["Продовження культового хіта"],
      developer: "Kojima Productions",
      platforms: ["Windows", "PlayStation"],
      price: undefined,
      image: undefined,
      description:
        "Екзистенціальна пригода від Хідео Кодзіми розширює межі інтерактивного кіно. Досліджуйте постапокаліптичний світ, будуйте інфраструктуру та розгадуйте таємниці 'побережжя'. Унікальний геймплей 'соціального стрендингу' та філософський сюжет.",
    },
    {
      id: "6",
      title: "GTA 5",
      originalPrice: "2,499,000 ₴",
      discountedPrice: "1,749,30 грн.",
      discount: 30,
      imageUrl: "/images/games/gta.png",
      tags: ["Очікувана подія року"],
      developer: "Rockstar Games",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Класика відкритого світу з тригерною історією трьох злочинців. Масивний Лос-Сантос, сотні побічних активностей та культова сатира на американське суспільство. GTA Online продовжує отримувати оновлення ще через 10+ років після виходу.",
    },
    {
      id: "7",
      title: "The Elder Scrolls VI",
      originalPrice: "2,299,000 ₴",
      discountedPrice: "1,724,25 грн.",
      discount: 25,
      imageUrl: "/images/games/elden.jpeg",
      tags: ["Відкритий світ", "RPG"],
      developer: "Bethesda Game Studios",
      platforms: ["Windows", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Довгоочікуване продовження найкращої RPG всіх часів. Дії відбуваються в провінції Хай-Рок з деталізованими системами магії, ремесла та фракцій. Гнучка система навичок дозволяє створювати унікальних персонажів. Мрія кожного RPG-фана.",
    },
    {
      id: "8",
      title: "Dragon Age: The Veilguard",
      originalPrice: "2,199,000 ₴",
      discountedPrice: "1,539,30 грн.",
      discount: 30,
      imageUrl: "/images/games/dragon.jpeg",
      tags: ["Тактична RPG", "Глибокий сюжет"],
      developer: "BioWare",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Повернення до фентезійного всесвіту Тедіс з покращеною бойовою системою та глибокими персонажами. Створюйте свого захисника, вербуйте союзників та приймайте морально складні рішення, які впливають на весь світ. Для шанувальників класичних cRPG.",
    },
    {
      id: "9",
      title: "Star Wars Outlaws",
      originalPrice: "2,399,000 ₴",
      discountedPrice: "1,679,30 грн.",
      discount: 30,
      imageUrl: "/images/games/wars.jpg",
      tags: ["Нове сяйво у всесвіті"],
      developer: "Quantic Dream",
      platforms: ["Windows", "PlayStation"],
      price: undefined,
      image: undefined,
      description:
        "Пригодницький екшен від творців Detroit: Become Human у всесвіті Зоряних Війн. Грайте за молодого контрабандиста, який намагається вижити між Імперією та Альянсом повстанців. Акцент на нарратив, діалоги та моральний вибір.",
    },
    {
      id: "10",
      title: "ghost of yotei",
      originalPrice: "1,999,000 ₴",
      discountedPrice: "1,399,30 грн.",
      discount: 30,
      imageUrl: "/images/games/ghost.avif",
      tags: ["Першокласна гра Obsidian"],
      developer: "Obsidian Entertainment",
      platforms: ["Windows", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Іммерсивна симуляція від Obsidian у стилі feudal Japan. Грайте за ніндзя з надприродніми здібностями, використовуючи стелс, паркур та матеріальну магію. Нелінійний світ з безліччю шляхів проходження та глибокою системой вибору.",
    },
    {
      id: "11",
      title: "Hollow Knight: Silksong",
      originalPrice: "999,000 ₴",
      discountedPrice: "749,25 грн.",
      discount: 25,
      imageUrl: "/images/games/silkson.avif",
      tags: ["Метроїдванія", "Продовження культу"],
      developer: "Team Cherry",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch"],
      price: undefined,
      image: undefined,
      description:
        "Довгоочікуване продовження культової метроїдванії. Грайте за Хорнет у новому королівстві Фарлум. Покращена бойова система, понад 150 нових ворогів та атмосферний саундтрек. Обов'язково для шанувальників оригіналу та любителів складних ігор.",
    },
    {
      id: "12",
      title: "Metroid Prime 4",
      originalPrice: "2,299,000 ₴",
      discountedPrice: "1,724,25 грн.",
      discount: 25,
      imageUrl: "/images/games/metroid.jpg",
      tags: ["Екшн-адвенчура", "Ексклюзив Nintendo"],
      developer: "Retro Studios",
      platforms: ["Nintendo Switch"],
      price: undefined,
      image: undefined,
      description:
        "Продовження легендарної серії шутерів від першої особи. Семус Аран повертається з новим обладнанням для дослідження чужих планет. Класичне поєднання стрільби, платформінгу та головоломок у стилі метроїдванії.",
    },
    {
      id: "13",
      title: "Black Myth: Wukong",
      originalPrice: "1,599,000 ₴",
      discountedPrice: "1,199,25 грн.",
      discount: 25,
      imageUrl: "/images/games/Black.jpg",
      tags: ["Китайська міфологія", "Складний екшн"],
      developer: "Game Science",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Епічний екшен-RPG на основі китайської класики 'Подорож на Захід'. Грайте за Короля Мавп Сунь Укуна, використовуючи 72 трансформації та магічні здібності. Вражаюча графіка, складні боси та автентичне відтворення міфології.",
    },
    {
      id: "14",
      title: "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
      originalPrice: "1,499,000 ₴",
      discountedPrice: "1,124,25 грн.",
      discount: 25,
      imageUrl: "/images/games/stalker.png",
      tags: ["Українська розробка", "Постапокаліпсис"],
      developer: "GSC Game World",
      platforms: ["Windows", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Продовження культового українського шутера з відкритим світом. Досліджуйте Чорнобильську зону відчуження, де фізика, біологія та аномальні явища створюють унікальний геймплей. A-Life 2.0 робить світ справді живим. Гордість української ігрової індустрії.",
    },
    {
      id: "15",
      title: "Fortnite",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "/images/games/fort.webp",
      tags: ["Battle Royale", "MONGIL:STAR DIVE"],
      developer: "Epic Games",
      platforms: [
        "Windows",
        "PlayStation",
        "Xbox",
        "Nintendo Switch",
        "Mobile",
      ],
      price: undefined,
      image: undefined,
      description:
        "Найпопулярніший battle royale з постійно оновлюваним контентом. Сезонні оновлення, крос-платформова гра та унікальна система будівництва. Ідеальний вибір для казуальних ігор з друзями та фанатів кросоверів з популярними франшизами.",
    },
    {
      id: "16",
      title: "Rocket League",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "/images/games/rocket.avif",
      tags: ["Tides of Annihilation", "Автофутбол"],
      developer: "Psyonix",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch"],
      price: undefined,
      image: undefined,
      description:
        "Унікальний спорт-симулятор, де автомобілі грають у футбол. Легка для вивчення, але майстерна для досконалості гра з високою майстерністю. Регулярні турніри, крос-платформова гра та тисячі предметів для кастомізації машин.",
    },
    {
      id: "17",
      title: "Hogwarts Legacy",
      originalPrice: "2,199,000 ₴",
      discountedPrice: "1,539,30 грн.",
      discount: 30,
      imageUrl: "/images/games/hogwarts.jpg",
      tags: ["Всесвіт Гаррі Поттера", "RPG"],
      developer: "Avalanche Software",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch"],
      price: undefined,
      image: undefined,
      description:
        "Відкритий світ RPG у всесвіті Гаррі Поттера. Грайте за студента Хогвартсу в 1800-х роках, вивчайте заклинання, приручайте магічних істот та розкривайте давні таємниці. Мрія кожного фаната поттеріани з ретельно відтвореними локаціями.",
    },
    {
      id: "18",
      title: "Subnautica 2",
      originalPrice: "1,599,000 ₴",
      discountedPrice: "1,199,25 грн.",
      discount: 25,
      imageUrl: "/images/games/subnautica-2.jpg",
      tags: ["Підводна адвенчура", "Виживання"],
      developer: "Unknown Worlds Entertainment",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Продовження культового симулятора виживання під водою. Досліджуйте нові океанічні світи, будуйте підводні бази та уникайте глибинних жахів. Покращена система крафтингу, кооператив на 4 особи та ще більше таємниць для розгадування.",
    },
    {
      id: "19",
      title: "GTA VI",
      originalPrice: "3,499,000 ₴",
      discountedPrice: "1,399,00 грн.",
      discount: 60,
      imageUrl: "/images/games/GTA_VI_Poster.jpg",
      tags: ["МЕГА АКЦІЯ", "Хіт десятиліття"],
      developer: "Rockstar Games",
      platforms: ["Windows", "PlayStation", "Xbox"],
      isMegaSale: true,
      saleEndsAt: "2026-01-20T23:59:59",
      price: undefined,
      image: undefined,
      description:
        "Найочікуваніша гра десятиліття від Rockstar Games. Повернення до Вайс-Сіті (прототип Маямі) з наймасштабнішим відкритим світом в історії ігор. Двоє головних героїв, революційна фізика, безліч нових механік та бездоганна сатира на сучасне суспільство. Купуйте зараз з мегазнижкою 60%!",
    },
    {
      id: "20",
      title: "Cyberpunk 2077: Ultimate Edition",
      originalPrice: "2,799,000 ₴",
      discountedPrice: "999,00 грн.",
      discount: 65,
      imageUrl: "/images/games/cyberpunk.avif",
      tags: ["МЕГА АКЦІЯ", "Повернення легенди"],
      developer: "CD Projekt RED",
      platforms: ["Windows", "PlayStation", "Xbox"],
      isMegaSale: true,
      saleEndsAt: "2026-01-20T23:59:59",
      price: undefined,
      image: undefined,
      description:
        "Повна версія кіберпанк RPG з усіма DLC та патчами. Після численних оновлень гра стала тим, що обіцяли - імерсивним відкритим світом з глибокими персонажами та захоплюючим сюжетом. Додаток Phantom Liberty додає шпигунський трилер з Айдрісом Ельбою. Не пропустіть знижку 65%!",
    },
    {
      id: "21",
      title: "Overwatch 2",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/540/thumbnail.jpg",
      tags: ["Командний шутер", "Герої"],
      developer: "Blizzard Entertainment",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch"],
      price: undefined,
      image: undefined,
      description:
        "Командний шутер від першої особи від Blizzard Entertainment. Оберіть одного з понад 30 унікальних героїв, кожен з яких має власні здібності, та змагайтеся в динамічних матчах 5 на 5. Регулярні сезонні оновлення, нові герої та режими.",
    },
    {
      id: "22",
      title: "Valorant",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/466/thumbnail.jpg",
      tags: ["Тактичний шутер", "5v5"],
      developer: "Riot Games",
      platforms: ["Windows"],
      price: undefined,
      image: undefined,
      description:
        "Тактичний шутер від Riot Games, де точна стрільба поєднується з унікальними здібностями агентів. Кожен раунд — це стратегічна дуель між атакуючими та захисниками. Один з найпопулярніших кіберспортивних шутерів у світі.",
    },
    {
      id: "23",
      title: "Genshin Impact",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/475/thumbnail.jpg",
      tags: ["Відкритий світ", "Action RPG"],
      developer: "miHoYo",
      platforms: ["Windows", "PlayStation", "Mobile"],
      price: undefined,
      image: undefined,
      description:
        "Масштабна Action RPG з відкритим світом від miHoYo. Досліджуйте фантастичний світ Тейват, збирайте команду з унікальних персонажів, освоюйте елементальну магію та розкривайте таємниці зниклого близнюка. Вражаюча графіка та глибока система бою.",
    },
    {
      id: "24",
      title: "Apex Legends",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/23/thumbnail.jpg",
      tags: ["Battle Royale", "Командний шутер"],
      developer: "Electronic Arts",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch"],
      price: undefined,
      image: undefined,
      description:
        "Стратегічний Battle Royale шутер на 60 гравців від Electronic Arts. Оберіть легенду з унікальними здібностями, об'єднайтесь у загін і змагайтеся за перемогу. Динамічний геймплей, пінг-система та постійні оновлення контенту.",
    },
    {
      id: "25",
      title: "League of Legends",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/286/thumbnail.jpg",
      tags: ["MOBA", "Кіберспорт"],
      developer: "Riot Games",
      platforms: ["Windows"],
      price: undefined,
      image: undefined,
      description:
        "Найпопулярніша MOBA у світі від Riot Games. Оберіть чемпіона зі 160+ персонажів, об'єднайтесь у команду 5v5 та знищте ворожий Нексус. Глибока стратегія, масштабні кіберспортивні турніри та постійні оновлення вже понад 15 років.",
    },
    {
      id: "26",
      title: "Destiny 2",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/21/thumbnail.jpg",
      tags: ["MMO шутер", "Sci-Fi"],
      developer: "Bungie",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Sci-Fi MMO шутер від Bungie з кінематографічним сюжетом. Досліджуйте Сонячну систему, збирайте легендарне спорядження, проходьте рейди з друзями та беріть участь у PvP-битвах. Величезний світ з постійно зростаючим контентом.",
    },
    {
      id: "27",
      title: "Lost Ark",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/517/thumbnail.jpg",
      tags: ["ARPG", "MMO"],
      developer: "Smilegate RPG",
      platforms: ["Windows"],
      price: undefined,
      image: undefined,
      description:
        "Масштабна MMOARPG від Smilegate та Amazon Games. Досліджуйте величезний світ Аркезії, оберіть один з 20+ класів, проходьте епічні рейди та PvP-арени. Кінематографічні бої, глибока система розвитку та сотні годин контенту.",
    },
    {
      id: "28",
      title: "Path of Exile",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/226/thumbnail.jpg",
      tags: ["ARPG", "Хардкор"],
      developer: "Grinding Gear Games",
      platforms: ["Windows"],
      price: undefined,
      image: undefined,
      description:
        "Хардкорна Action RPG у стилі Diablo від Grinding Gear Games. Унікальна система пасивних навичок з понад 1300 вузлами, сезонні ліги з новими механіками та безкоштовна модель без pay-to-win. Одна з найглибших RPG-систем в індустрії.",
    },
    {
      id: "29",
      title: "Warframe",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/3/thumbnail.jpg",
      tags: ["Sci-Fi шутер", "Кооператив"],
      developer: "Digital Extremes",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch"],
      price: undefined,
      image: undefined,
      description:
        "Кооперативний шутер від третьої особи у Sci-Fi всесвіті від Digital Extremes. Керуйте воїнами Тенно, використовуйте Warframe-екзоскелети з унікальними здібностями та вирушайте на місії по всій Сонячній системі. Один з найщедріших F2P проєктів.",
    },
    {
      id: "30",
      title: "Counter-Strike 2",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/24/thumbnail.jpg",
      tags: ["Тактичний шутер", "Кіберспорт"],
      developer: "Valve",
      platforms: ["Windows"],
      price: undefined,
      image: undefined,
      description:
        "Легендарний тактичний шутер від Valve на оновленому движку Source 2. Покращена графіка, нова система димових гранат та тікрейт, але той самий культовий геймплей, що зробив CS найпопулярнішим шутером в історії. Головна кіберспортивна дисципліна.",
    },
    {
      id: "31",
      title: "Dota 2",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/229/thumbnail.jpg",
      tags: ["MOBA", "Стратегія"],
      developer: "Valve",
      platforms: ["Windows"],
      price: undefined,
      image: undefined,
      description:
        "Конкурентна MOBA від Valve з найбільшим призовим фондом в кіберспорті. 120+ героїв, безмежні стратегічні можливості та команди 5v5. Кожен матч — унікальна партія зі складними комбінаціями предметів, навичок та тактик.",
    },
    {
      id: "32",
      title: "PUBG: BATTLEGROUNDS",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/516/thumbnail.jpg",
      tags: ["Battle Royale", "Реалістичний"],
      developer: "KRAFTON, Inc.",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Піонер жанру Battle Royale. 100 гравців десантуються на острів, збирають спорядження та борються до останнього. Реалістична балістика, великі карти та напружені фінальні зони. Гра, що створила цілий жанр і залишається актуальною.",
    },
    {
      id: "33",
      title: "Call of Duty: Warzone",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/452/thumbnail.jpg",
      tags: ["Battle Royale", "FPS"],
      developer: "Infinity Ward",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Безкоштовний Battle Royale у всесвіті Call of Duty. Масштабні битви на 150 гравців, система Gulag для другого шансу, контракти та динамічні події на карті. Швидкий геймплей та зброя з культової серії CoD.",
    },
    {
      id: "34",
      title: "Honkai: Star Rail",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/605/thumbnail.jpg",
      tags: ["RPG", "Покрокова"],
      developer: "HoYoverse",
      platforms: ["Windows", "PlayStation", "Mobile"],
      price: undefined,
      image: undefined,
      description:
        "Sci-Fantasy RPG від HoYoverse з покроковою бойовою системою. Подорожуйте галактичним експресом, збирайте команду унікальних персонажів та розкривайте таємниці зоряних світів. Глибокий сюжет, стильна графіка та стратегічні бої.",
    },
    {
      id: "35",
      title: "Marvel Rivals",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/599/thumbnail.jpg",
      tags: ["Командний шутер", "Супергерої"],
      developer: "NetEase",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Командний шутер від NetEase у всесвіті Marvel. Грайте за улюблених героїв та лиходіїв — від Людини-Павука до Магнето — в динамічних PvP-матчах. Руйнівне оточення, командні комбо-атаки та унікальні здібності кожного персонажа.",
    },
    {
      id: "36",
      title: "The Finals",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/570/thumbnail.jpg",
      tags: ["FPS", "Руйнування"],
      developer: "Embark Studios",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "PvP-шутер у стилі ігрового шоу від Embark Studios. Повністю руйнівне оточення, три класи персонажів та кілька унікальних режимів. Стріляйте крізь стіни, обвалюйте будівлі на ворогів та використовуйте середовище як зброю.",
    },
    {
      id: "37",
      title: "Brawlhalla",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/212/thumbnail.jpg",
      tags: ["Файтинг", "Платформер"],
      developer: "Blue Mammoth Games",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch", "Mobile"],
      price: undefined,
      image: undefined,
      description:
        "2D-платформний файтинг, натхненний Super Smash Bros. Понад 50 унікальних легенд, крос-платформна гра та кросовери з Kung Fu Panda, WWE, Tomb Raider та іншими франшизами. Легкий для вивчення, але глибокий для майстрів.",
    },
    {
      id: "38",
      title: "Fall Guys",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/523/thumbnail.jpg",
      tags: ["Party Game", "Battle Royale"],
      developer: "Mediatonic",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch"],
      price: undefined,
      image: undefined,
      description:
        "Найвеселіший масовий мультиплеєр! 60 гравців-бобів змагаються в божевільних перешкодах, гонках та командних іграх. Кожен раунд — нове випробування, а переможець отримує корону. Ідеальна гра для вечірок з друзями.",
    },
    {
      id: "39",
      title: "Guild Wars 2",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/13/thumbnail.jpg",
      tags: ["MMORPG", "Відкритий світ"],
      developer: "ArenaNet",
      platforms: ["Windows"],
      price: undefined,
      image: undefined,
      description:
        "Масштабна MMORPG від ArenaNet без щомісячної підписки. Величезний відкритий світ Тірії, динамічні події, WvW-битви сотень гравців та елегантна бойова система. Одна з найкращих MMO з акцентом на горизонтальний прогрес.",
    },
    {
      id: "40",
      title: "War Thunder",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "https://www.freetogame.com/g/12/thumbnail.jpg",
      tags: ["Військовий симулятор", "MMO"],
      developer: "Gaijin Entertainment",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
      description:
        "Військовий MMO-симулятор з танками, літаками та кораблями від Gaijin Entertainment. Сотні реалістично відтворених бойових машин Другої світової та сучасності. Різні режими реалізму — від аркадного до повного симулятора.",
    },
  ];
};
