import { Game } from "@/types/game";

export const getSaleGames = (): Game[] => {
  return [
    {
      id: "1",
      title: "Battlefield™ 6",
      originalPrice: "1,699,000 ₴",
      discountedPrice: "1,189,30 грн.",
      discount: 30,
      imageUrl: "/images/games/battlefield-6.jpg",
      tags: ["Гостине", "Норвегія Liquacy"],
      developer: "EA DICE",
      platforms: ["Windows"],
      price: undefined,
      image: undefined,
    },
    {
      id: "2",
      title: "EA SPORTS FC™ 28 Standard Edition",
      originalPrice: "1,699,000 ₴",
      discountedPrice: "673,00 грн.",
      discount: 60,
      imageUrl: "/images/games/fc28.jpg",
      tags: ["Доступний пробний період"],
      developer: "EA Sports",
      platforms: ["Windows", "PlayStation"],
      price: undefined,
      image: undefined,
    },
    {
      id: "3",
      title: "Borderlands 4",
      originalPrice: "2,099,000 ₴",
      discountedPrice: "1,469,30 грн.",
      discount: 30,
      imageUrl: "/images/games/borderlands-4-fnnpo.jpg",
      tags: ["Провальний хіт став легендою"],
      developer: "Gearbox Software",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
    },
    {
      id: "4",
      title: "ARK: Riders",
      originalPrice: "1,499,000 ₴",
      discountedPrice: "1,049,30 грн.",
      discount: 30,
      imageUrl: "/images/games/arc.avif",
      tags: ["Новий світ, нові пригоди"],
      developer: "Studio Wildcard",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
    },
    {
      id: "5",
      title: "Death Stranding 2",
      originalPrice: "2,299,000 ₴",
      discountedPrice: "1,609,30 грн.",
      discount: 30,
      imageUrl: "/images/games/death.jpg",
      tags: ["Продовження культового хіта"],
      developer: "Kojima Productions",
      platforms: ["Windows", "PlayStation"],
      price: undefined,
      image: undefined,
    },
    {
      id: "6",
      title: "GTA 5",
      originalPrice: "2,499,000 ₴",
      discountedPrice: "1,749,30 грн.",
      discount: 30,
      imageUrl: "/images/games/gta.png",
      tags: ["Очікувана подія року"],
      developer: "Rockstar Games",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
    },
    {
      id: "7",
      title: "The Elder Scrolls VI",
      originalPrice: "2,299,000 ₴",
      discountedPrice: "1,724,25 грн.",
      discount: 25,
      imageUrl: "/images/games/elden.jpeg",
      tags: ["Відкритий світ", "RPG"],
      developer: "Bethesda Game Studios",
      platforms: ["Windows", "Xbox"],
      price: undefined,
      image: undefined,
    },
    {
      id: "8",
      title: "Dragon Age: The Veilguard",
      originalPrice: "2,199,000 ₴",
      discountedPrice: "1,539,30 грн.",
      discount: 30,
      imageUrl: "/images/games/dragon.jpeg",
      tags: ["Тактична RPG", "Глибокий сюжет"],
      developer: "BioWare",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
    },
    {
      id: "9",
      title: "Star Wars Outlaws",
      originalPrice: "2,399,000 ₴",
      discountedPrice: "1,679,30 грн.",
      discount: 30,
      imageUrl: "/images/games/wars.jpg",
      tags: ["Нове сяйво у всесвіті"],
      developer: "Quantic Dream",
      platforms: ["Windows", "PlayStation"],
      price: undefined,
      image: undefined,
    },
    {
      id: "10",
      title: "ghost of yotei",
      originalPrice: "1,999,000 ₴",
      discountedPrice: "1,399,30 грн.",
      discount: 30,
      imageUrl: "/images/games/ghost.avif",
      tags: ["Першокласна гра Obsidian"],
      developer: "Obsidian Entertainment",
      platforms: ["Windows", "Xbox"],
      price: undefined,
      image: undefined,
    },
    {
      id: "11",
      title: "Hollow Knight: Silksong",
      originalPrice: "999,000 ₴",
      discountedPrice: "749,25 грн.",
      discount: 25,
      imageUrl: "/images/games/silkson.avif",
      tags: ["Метроїдванія", "Продовження культу"],
      developer: "Team Cherry",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch"],
      price: undefined,
      image: undefined,
    },
    {
      id: "12",
      title: "Metroid Prime 4",
      originalPrice: "2,299,000 ₴",
      discountedPrice: "1,724,25 грн.",
      discount: 25,
      imageUrl: "/images/games/metroid.jpg",
      tags: ["Екшн-адвенчура", "Ексклюзив Nintendo"],
      developer: "Retro Studios",
      platforms: ["Nintendo Switch"],
      price: undefined,
      image: undefined,
    },
    {
      id: "13",
      title: "Black Myth: Wukong",
      originalPrice: "1,599,000 ₴",
      discountedPrice: "1,199,25 грн.",
      discount: 25,
      imageUrl: "/images/games/Black.jpg",
      tags: ["Китайська міфологія", "Складний екшн"],
      developer: "Game Science",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
    },
    {
      id: "14",
      title: "S.T.A.L.K.E.R. 2: Heart of Chornobyl",
      originalPrice: "1,499,000 ₴",
      discountedPrice: "1,124,25 грн.",
      discount: 25,
      imageUrl: "/images/games/stalker.png",
      tags: ["Українська розробка", "Постапокаліпсис"],
      developer: "GSC Game World",
      platforms: ["Windows", "Xbox"],
      price: undefined,
      image: undefined,
    },
    {
      id: "15",
      title: "Fortnite",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "/images/games/fort.webp",
      tags: ["Battle Royale", "MONGIL:STAR DIVE"],
      developer: "Epic Games",
      platforms: [
        "Windows",
        "PlayStation",
        "Xbox",
        "Nintendo Switch",
        "Mobile",
      ],
      price: undefined,
      image: undefined,
    },
    {
      id: "16",
      title: "Rocket League",
      originalPrice: "Безкоштовна",
      discountedPrice: "Безкоштовна",
      discount: 0,
      imageUrl: "/images/games/rocket.avif",
      tags: ["Tides of Annihilation", "Автофутбол"],
      developer: "Psyonix",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch"],
      price: undefined,
      image: undefined,
    },
    {
      id: "17",
      title: "Hogwarts Legacy",
      originalPrice: "2,199,000 ₴",
      discountedPrice: "1,539,30 грн.",
      discount: 30,
      imageUrl: "/images/games/hogwarts.jpg",
      tags: ["Всесвіт Гаррі Поттера", "RPG"],
      developer: "Avalanche Software",
      platforms: ["Windows", "PlayStation", "Xbox", "Nintendo Switch"],
      price: undefined,
      image: undefined,
    },
    {
      id: "18",
      title: "Subnautica 2",
      originalPrice: "1,599,000 ₴",
      discountedPrice: "1,199,25 грн.",
      discount: 25,
      imageUrl: "/images/games/subnautica-2.jpg",
      tags: ["Підводна адвенчура", "Виживання"],
      developer: "Unknown Worlds Entertainment",
      platforms: ["Windows", "PlayStation", "Xbox"],
      price: undefined,
      image: undefined,
    },
  ];
};
